import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { generateChecklist, getProvider } from '@/lib/ai';

export const dynamic = 'force-dynamic';

// POST /api/spec-workflow/checklist - Generate checklist and save to database
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { projectId, featureId, name, specContent, planContent, tasksContent, theme } = body;

    if (!projectId) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }

    if (!featureId) {
      return NextResponse.json({ error: 'Feature ID is required' }, { status: 400 });
    }

    if (!specContent || !planContent) {
      return NextResponse.json({ error: 'Spec and plan content required' }, { status: 400 });
    }

    // Verify project exists
    const project = await prisma.project.findUnique({ where: { id: projectId } });
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const provider = await getProvider();
    const checklist = await generateChecklist({ specContent, planContent, tasksContent, theme });

    // Generate markdown content from checklist items
    const checklistsContent = generateChecklistMarkdown(checklist, name || 'Feature');

    // Save checklistsContent to database - don't update stage (plan API already set it to 'plan')
    await prisma.feature.update({
      where: { id: featureId },
      data: {
        checklistsContent
      }
    });

    return NextResponse.json({
      step: 'checklist',
      checklist: {
        theme: checklist.theme,
        itemCount: checklist.items.length,
      },
      content: checklistsContent,
      featureId,
    });

  } catch (error) {
    console.error('[API] Checklist generation error:', error);

    if (error instanceof Error) {
      if (error.message.includes('API key')) {
        return NextResponse.json({ error: error.message }, { status: 401 });
      }
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ error: 'Failed to generate checklist' }, { status: 500 });
  }
}

// Generate markdown content from checklist items
function generateChecklistMarkdown(checklist: { theme: string; items: Array<{ id: string; question: string; category: string; reference?: string }> }, featureName: string): string {
  const lines = [
    `# Checklist - ${featureName}`,
    ``,
    `> Generated by AI - "Unit Tests for Requirements"`,
    `> Theme: ${checklist.theme}`,
    ``,
    `## Quality Dimensions`,
    ``,
  ];

  // Group items by category
  const byCategory: Record<string, typeof checklist.items> = {};
  for (const item of checklist.items) {
    if (!byCategory[item.category]) {
      byCategory[item.category] = [];
    }
    byCategory[item.category].push(item);
  }

  // Output by category
  for (const [category, items] of Object.entries(byCategory)) {
    lines.push(`### ${category}`);
    for (const item of items) {
      const ref = item.reference ? ` ${item.reference}` : '';
      lines.push(`- [ ] ${item.id} - ${item.question}${ref}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
